server:
  port: 8080

spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jdbc:
    template:
      fetch-size: 100


logging:
  level:
    org.springframework.ai: DEBUG
    com.example.genaistudentscore: DEBUG

grok:
  api:
    url: https://api.x.ai/v1/responses   # <-- update with your actual Grok API URL
    key: ${GROK_API_KEY}               # <-- update with your actual Grok API key
